apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
spec:
  template:
    spec:
      containers:
        - name: billing-service
          image: 744561091152.dkr.ecr.us-east-1.amazonaws.com/zerotheft/zt-be-billing-service:staging
