apiVersion: v1
kind: Service
metadata:
  name: tenant-app
  labels:
    app: tenant-app
spec:
  selector:
    app: tenant-app
  ports:
    - port: 80
      targetPort: 3000
      name: http
  type: ClusterIP
