apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-app
spec:
  template:
    spec:
      containers:
        - name: tenant-app
          image: 744561091152.dkr.ecr.us-east-1.amazonaws.com/zerotheft/zt-fe-tenant-app:stable
