apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  template:
    spec:
      containers:
        - name: notification-service
          image: 744561091152.dkr.ecr.us-east-1.amazonaws.com/zerotheft/zt-be-notification-service:staging
