apiVersion: v1
kind: Service
metadata:
  name: audit-service
  labels:
    app: audit-service
spec:
  selector:
    app: audit-service
  ports:
    - port: 80
      targetPort: 8003
      name: http
  type: ClusterIP
