apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-discovery-service
spec:
  template:
    spec:
      containers:
        - name: device-discovery-service
          image: 744561091152.dkr.ecr.us-east-1.amazonaws.com/zerotheft/zt-inf-device-discovery-service:latest
