apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zerotheft-dev

resources:
  - ../../base
  - serviceaccount.yaml

patches:
  - path: image-tag.yaml
  - path: replica-count.yaml
  - path: vault-injection.yaml

namePrefix: dev-

commonLabels:
  environment: dev
