apiVersion: v1
kind: Service
metadata:
  name: billing-service
  labels:
    app: billing-service
spec:
  selector:
    app: billing-service
  ports:
    - port: 80
      targetPort: 8002
      name: http
  type: ClusterIP
