apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-app
spec:
  template:
    spec:
      containers:
        - name: flutter-app
          image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/zerotheft/zt-mo-app:staging
